
services:
  app:
    build: ./vault
    container_name: vault-app
    restart: unless-stopped
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - ${SHARED_DATA_PATH}:/app/shared_data
    depends_on:
      - mariadb
      - nginx
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    pull_policy: if_not_present  # 或者使用 if_not_present, always, never
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    env_file:
      - .env # 从 .env 文件加载环境变量 容器环境变量默认加载.env 文件, 指定其他文件不会加载到容器环境变量中
    # 如果上面文件 .env 中的变量名和容器需要的变量名一致，就不需要下面的 environment 了
    # 如果使用其它的文件名如mariadb.env,里面的变量不会自动加载到容器环境变量中，下面的都会使用默认值
    # 环境变量加载优先级：
      # 1. environment 中直接定义的变量
      # 2. env_file 中加载的变量
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-admin} # 如果变量不存在，使用默认值
      DB_DATABASE: ${DB_DATABASE:-mydb}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      TZ: Asia/Shanghai
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/config:/etc/mysql/conf.d
      - ./mariadb/initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=1000

  # Nginx代理服务器
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8010:8010"
      - "9000:9000"
    env_file:
        - ./nginx/.env
    volumes:
      - ./nginx/www:/usr/share/nginx/www:ro # read-only（只读）
      - ./nginx/certs:/etc/nginx/certs # read-only（只读）
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ${SHARED_DATA_PATH}:/usr/share/nginx/shared_data:ro # read-only（只读）
      - nginx-logs:/var/log/nginx	# 日志卷 - Docker 自动管理
#    depends_on:
#      - flask-app
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/nginx-health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mosquitto:
    image: eclipse-mosquitto:2.0.22-openssl
    container_name: mosquitto
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${MQTT_PORT:-1883}:1883"     # MQTT
      - "${MQTTS_PORT:-8883}:8883"    # MQTT over SSL
      - "${MQTT_WebSocket_PORT:-9010}:9010" # WebSocket
      - "${MQTTS_WebSocket_PORT:-9011}:9011" # WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/certs:/mosquitto/certs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Docker 自动管理 卷
volumes:
  nginx-logs:
    driver: local